language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.7.5 UPDATE_REPOSITORY="true" LD_LIBRARY_PATH=/usr/local/petsc/lib
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.7.5 UPDATE_REPOSITORY="add-apt-repository -y ppa:octave/stable"
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.7.6 UPDATE_REPOSITORY="true" LD_LIBRARY_PATH=/usr/local/petsc/lib
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.7.6 UPDATE_REPOSITORY="add-apt-repository -y ppa:octave/stable"
    - os: osx
      env: PETSC_VERSION=3.7.6 LD_LIBRARY_PATH=/usr/local/petsc/lib

before_install:
# Install Octave and MATLAB
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo $UPDATE_REPOSITORY;
        sudo apt-get update -q;
        sudo apt-get install -y --no-install-recommends
           octave
           bsdtar
           liboctave-dev
           mpich2
           libmpich2-dev
           build-essential
           gfortran
           cmake
           bison
           flex
           libboost-filesystem-dev
           libboost-iostreams-dev
           libboost-program-options-dev
           libboost-system-dev
           libboost-thread-dev
           libboost-timer-dev;
       curl -L "$URL" | sudo bsdtar zxf - -C /usr/local --strip-components 2;
       sudo ln -s -f /usr/local/MATLAB/R2016b/bin/matlab /usr/local/bin;
       sudo ln -s -f /usr/local/MATLAB/R2016b/bin/mex /usr/local/bin;
     fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         brew tap homebrew/science;
         brew update;
         brew install --without-java octave;
         brew install
           mpich2
           gfortran
           cmake
           bison
           flex
           boost;
     fi'
# Inatall paracoder
  - 'cd .. &&
     mkdir -p paracoder &&
     curl -s  -L https://github.com/fastsolve/paracoder/archive/master.zip |
         bsdtar zxf - --strip-components 1 -C paracoder &&
     cd paracoder &&
     octave --eval "build_m2c -force" &&
     [[ "$TRAVIS_OS_NAME" == "linux" ]] &&  octave --eval "build_m2c -force -matlab" &&
     cd ../petsc4m'

script:
# Build PETSc
  - 'curl -s http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-${PETSC_VERSION}.tar.gz |
          tar zx &&
     cd petsc-${PETSC_VERSION} &&
     ./configure --COPTFLAGS="-g" --CXXOPTFLAGS="-g" --FOPTFLAGS="-g"
        --with-c-support --with-debugging=1 --with-shared-libraries
        --download-blas --download-lapack
        --download-suitesparse --download-superlu
        --download-superlu_dist --download-scalapack
        --download-metis --download-parmetis
        --download-ptscotch --download-hypre
        --download-mumps --download-blacs
        --download-spai --download-ml --prefix=/usr/local/petsc'
  - make && sudo make install && cd ..

# compile petsc4m
  - PETSC_DIR=/usr/local/petsc octave --eval "build_petsc -force"
  - '[[ "$TRAVIS_OS_NAME" == "linux" ]] &&
     PETSC_DIR=/usr/local/petsc octave --eval "build_petsc -force -matlab"'
