language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.7.7 UPDATE_REPOSITORY="true" LD_LIBRARY_PATH=$HOME/petsc/lib
    - os: linux
      dist: trusty
      sudo: required
      env: PETSC_VERSION=3.8.3 UPDATE_REPOSITORY="true" LD_LIBRARY_PATH=$HOME/petsc/lib

before_install:
  # Install Octave and MATLAB
  - '[[ "$TRAVIS_OS_NAME" != "linux" ]] || echo $(ifconfig eth0 | grep HWaddr)'
  - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || echo $(ifconfig en0 | grep ether)'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo $UPDATE_REPOSITORY;
        sudo apt-get update -q;
        sudo apt-get install -y --no-install-recommends
           realpath
           octave
           bsdtar
           liboctave-dev
           mpich2
           libmpich2-dev
           build-essential
           gfortran
           cmake
           bison
           flex;
       pip install -U requests;
       [[ "$BUILD_MATLAB" == "0" ]] || (curl -s -L
       https://raw.githubusercontent.com/hpdata/gdutil/master/gd_get_pub.py |
       python - -o - -i "$MEX_LINUX" |
       sudo bsdtar zxf - -C /usr/local --strip-components 2;
       sudo ln -s -f /usr/local/MATLAB/R*/bin/mex /usr/local/bin);
     fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        pip install -U requests;
        [[ "$BUILD_MATLAB" == "0" ]] || (curl -s -L
        https://raw.githubusercontent.com/hpdata/gdutil/master/gd_get_pub.py |
        python - -o - -i "$MEX_OSX" |
        sudo bsdtar zxf - -C /Applications --strip-components 1;
        sudo ln -s -f /Applications/MATLAB_R*/bin/mex /usr/local/bin);
        brew tap homebrew/science;
        brew update;
        brew install --without-java octave;
        brew install mpich2 flex;
        sudo ln -s -f /usr/local/bin/gcc-7 /usr/local/bin/gcc-mp;
        sudo ln -s -f /usr/local/bin/g++-7 /usr/local/bin/g++-mp;
        sudo ls -l /usr/local/bin/gcc-* /usr/local/bin/g++-*;
     fi'

 # Build PETSc
  - 'curl -s http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-${PETSC_VERSION}.tar.gz |
          tar zx &&
     cd petsc-${PETSC_VERSION} &&
     ./configure --COPTFLAGS="-g" --CXXOPTFLAGS="-g" --FOPTFLAGS="-g"
        --with-c-support --with-debugging=1 --with-shared-libraries
        --download-blas --download-lapack
        --download-suitesparse --download-superlu
        --download-scalapack
        --download-metis --download-parmetis
        --download-ptscotch --download-hypre
        --download-mumps --download-blacs
        --download-spai --prefix=$HOME/petsc'
  - make && sudo make install && cd ..

script:
  # Inatall paracoder
  - 'cd .. &&
     mkdir -p paracoder &&
     curl -s  -L https://github.com/fastsolve/paracoder/archive/master.zip |
         bsdtar zxf - --strip-components 1 -C paracoder &&
     cd paracoder &&
     cd ../petsc4m'

  # compile and test petsc4m
  - '[[ "$BUILD_MATLAB" == "1" ]] || PETSC_DIR=$HOME/petsc octave --eval "build_petsc -force; run tests/test_petsc"'
  # '[[ "$BUILD_MATLAB" == "0" ]] || PETSC_DIR=$HOME/petsc octave --eval "build_petsc -force -matlab"'
